### ISSUE TITLE
Support LINQ query generation

### ISSUE THREAD

**Issue by kirankumarkolli** [Azure/azure-cosmos-dotnet-v3#212]
**Describe the solution you'd like**
Cosmos SQL query generation through LINQ over domain POCO types enables typed query generation. Its an awesome convenience feature requested through user-feed as well. 

LINQ in .standard 2.0 does a blocking execution. SDK supports LINQ query generation and an optional opt-in execution. 

**Task List**
- [ ] @simplynaveen20 new API which enabled LINQ composition (i.e. returned IOrderedByQueryable)
- [ ] @simplynaveen20 LINQ execution by-default throws NotSupportedException with details to "opt-in or async execute reference"
- [ ] @simplynaveen20 LINQ execution when opted-in explictly
- [ ] @simplynaveen20 LINQ execution to leverage V3 pipeline

**Comment by kirankumarkolli** [comment]
#208

**Comment by kirankumarkolli** [comment]
#26

**Comment by kirankumarkolli** [comment]
#55 #4 #208

**Comment by vip32** [comment]
please also support the newest OFFSET and LIMIT operators (skip/take)

**Comment by vip32** [comment]
very nice!
