### ISSUE TITLE
Make PartitionKey an optional argument when possible [Create/Replace]

### ISSUE THREAD

**Issue by kirankumarkolli** [Azure/azure-cosmos-dotnet-v3#230]
**Is your feature request related to a problem? Please describe.**
[Create/Replace]ItemAsync  demand PartitonKey as arguments, not necessary. 

**Describe the solution you'd like**
Change contracts to
```C#
public abstract Task<CosmosItemResponse<T>> CreateItemAsync<T>(
  T item,
  object partiotnKey,
  CosmosItemRequestOptions requestOptions = null,
  CancellationToken cancellationToken = default(CancellationToken));

public abstract Task<CosmosItemResponse<T>> ReplaceItemAsync<T>(
  string id,
  T item,
  object partiotnKey,
  CosmosItemRequestOptions requestOptions = null,
  CancellationToken cancellationToken = default(CancellationToken));
```

Implementation will extract the required PartitionKey argument when necessary. 
- Extraction PartitionKey from stream (covering custom serialization). Great convenience.
- Optional 'PartitionKey' to override

Suggested implementation flow will be like
* Use (partitionKey != null)
* Extract PartitionKey
  * Extract from stream
  * When used with DefaultSerializer, extract during serialization (optimization)

**Task List**
- [x] Optional partitonKey for Create/Upsert/ReplaceItem<T> (#331)
- [x] Extract partitionKey from stream (#335 )
- [x] In-consistent resource addressing between hierarchy and HA layer (#340 )
- [ ] [Optimization] Extarct PartitionKey during default serialization 
- [ ] [Optimization] Minimal memory allocations (#341 )
- [ ] Direct default cache version handling (#342 )

**Comment by kirankumarkolli** [comment]
Feature is ready to use, hence closing it. 
Optimizations are tracked separately.
