### ISSUE TITLE
Client Retry Policy: Handle HTTP timeouts with request-level cross-region retry

### ISSUE THREAD

**Issue by ealsur** [Azure/azure-cosmos-dotnet-v3#3497]
Reference: https://github.com/Azure/azure-cosmos-dotnet-v3/issues/3467

After retries have been exhausted, the `CosmosHttpClientCore` component should throw a 503 with the HTTP timeout as inner exception.

The 503 should reach the ClientRetryPolicy and be handled like 503s are right now: https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/src/ClientRetryPolicy.cs#L250

Identify which `HttpTimeoutPolicy` is used for each of the cases:

* Data Plane
* Metadata
* Query Plan
* Address requests

For the cases described in the referenced table (pasting here for easy access), we should convert the last timeout into a 503 with the timeout as an InnerException:

| Type | Read/Write | 
|----------|------------|
| Data plane |  Read |
| Data plane |  Write |
| Metadata |  Read | |
|  Query Plan | Read (it is always read) | 

## Tasks
- [ ] Complete use case scenarios
- [ ] Sequence diagram
- [ ] Presentation and design discussion
- [ ] Define deliverables, delivery date and project milestone

## Use case scenarios

| Data plan in Gateway mode for Reads, Request Timeout |
|----|
| Given a CX wants to read an existing item |
| When I configure my _CosmosClient.ConnectionMode_ for **Gateway** mode (which uses an HTTP protocol) |
|    - And it will send the operational request using _SendHttpHelperAsync_ |
|    - And the retries will throw a 408 (Request Timeout) exception |
|    - And the retries have exhausted to its limits |
| Then the 408 (Request Timeout) exception is converted to a 503 (Service Unavailable) exception |

| Data plan in Gateway mode for Reads, Not Found |
|----|
| Given a CX wants to read an item that does not exist |
| When I configure my _CosmosClient.ConnectionMode_ for **Gateway** mode (which uses an HTTP protocol) |
|    - And it will send the operational request using _SendHttpHelperAsync_ |
| Then the 404 (Not Found) exception is thrown |

| Data plan in Gateway mode for Writes, Request Timeout |
|----|
| Given a CX wants to write a new item (should test all of the following: CREATE, DELETE, REPLACE, UPSERT, PATCH, etc.) |
| When I configure my _CosmosClient.ConnectionMode_ for **Gateway** mode (which uses an HTTP protocol) |
|    - And it will send the operational request using _SendHttpHelperAsync_ |
|    - And the retries will throw a 408 (Request Timeout) exception |
|    - And the retries have exhausted to its limits |
| Then the 408 (Request Timeout) exception is converted to a 503 (Service Unavailable) exception |

| Data plan in Gateway mode for Writes, Conflict |
|----|
| Given a CX wants to create an item that already exist |
| When I configure my _CosmosClient.ConnectionMode_ for **Gateway** mode (which uses an HTTP protocol) |
|    - And it will send the operational request using _SendHttpHelperAsync_ |
| Then the 409 (Not Found) exception is thrown |

| Data plan in Gateway mode for Reads, Request Timeout |
|----|
| Given a CX wants to read an existing item |
| When I configure my _CosmosClient.ConnectionMode_ for **Gateway** mode (which uses an HTTP protocol) |
|    - And it will send the operational request using _SendHttpHelperAsync_ |
|    - And the retries will throw a 408 (Request Timeout) exception |
|    - And the retries have exhausted to its limits |
| Then the 408 (Request Timeout) exception is converted to a 503 (Service Unavailable) exception |

## Clarifying questions
- Do we need to be concerned with sub status codes?
- Just need to clarify that we are not including a solution for Direct Mode.
  - https://github.com/Azure/azure-cosmos-dotnet-v3/issues/3467
- How to exhaust all retries so that it returns a 408 (Request Timeout) exception?
- What is the best means for testing a Metadata Read operation request?
- What kind of exceptions, other than a 408 (Request Timeout), could occur with a Metadata Read?
- What is the best means for testing a Query Plan operation request?
- What kind of exceptions, other than a 408 (Request Timeout), could occur with a Query Plan?
- Should we also be testing this for Change Feed iterator/estimator?

This would mean adapting the HttpTimeoutPolicy interface to know which cases should throw the 503 or which should throw the normal timeout: https://github.com/Azure/azure-cosmos-dotnet-v3/blob/1eaae654845f83faf3283ee3be53d8d2c31e5256/Microsoft.Azure.Cosmos/src/HttpClient/CosmosHttpClientCore.cs#L295

**Comment by NaluTripician** [comment]
# Background #
Right now this is the current flow of operations for HTTP operations in gateway mode when they timeout. 

```mermaid
sequenceDiagram
    participant A as Operation
    participant B as ClientRetryPolicy <br> [Cross region retry]
    participant C as TransportHandler
    participant D as HttpTimeoutPolicy
    participant E as CosmosHttpClientCore
    A->>B: 1. Send HTTP operation
    B->>C: 
    C->>D: Wraps the call around retry layer
    D->>E: 
    E-->>D: OperationCanceledException
    D-->>E: Retries HTTP timeouts on same endpoint
    D-->>D: Repeats until retries exhausted
    D->>C: OperationCanceledException
    C->>B: CosmosException(408)
    B->>A: 
```

## Why we need to change this ##
Currently, the SDKs don't factor HTTP timeouts in their cross-regional retry policies. TCP timeouts are covered but HTTP timeouts are only retried locally and then surface to the user.

Because HTTP timeouts do not have any cross-region failover semantics, SDKs could not attempt to recover by rerouting requests to other available regions. Some HTTP operations can be performed on other regions and therefore should be retried.

Here is a list of the different HTTP operations that the SDKs preforms. 

| Type | Read/Write | Multi Master | Can be retried? |
|----------|------------|--------------|-----------------|
| Data plane |  Read | No | Yes |
| Data plane |  Write | No | No |
| Data plane |  Read | Yes | Yes |
| Data plane |  Write | Yes | Yes |
| Metadata |  Read | No | Yes |
| Metadata |  Write | No | No |
| Metadata |  Read | Yes | Yes |
| Metadata |  Write | Yes | No |
|  Query Plan | Read | No | Yes |
|  Query Plan | Read | Yes | Yes |
|  Addresses | Read | No | No |
|  Addresses | Read | Yes | No |


So, out of these operations the ones that are retriable are the following. 

| Type | Read/Write | 
|----------|------------|
| Data plane |  Read |
| Data plane |  Write |
| Metadata |  Read | |
|  Query Plan | Read (it is always read) | 

## What needs to change? ## 

Looking at the current flow we can see that each HTTP operation is assigned a HttpTimeoutPolicy which dictates its behavior on a timeout. So we need a way to tell the timeout policy if it is one of these types of HTTP operations that can be retried with a 503 status code it should. 

If we follow the same pattern that we have in the Direct mode (retry locally, if retries are exhausted, throw 503), if the HttpTimeoutPolicy converted the HTTP timeout to 503, then it would kickoff the retry on another region. Because each HttpTimeoutPolicy is aware of the type of operation upon initiation, then it can conditionally decide whether to make the timeout a 503 or not if one were to occur.

# HTTP Timeout Policies #

There are 4 different types of HTTP Timeout Policies so we need to look at what they are used for and see if they need to change. 

## NoRetry ##
This policy is used for HTTP requests that should not be retried. Because it should never be retried it does not need to change. 

## ControlPlaneRead ##

Here because all control plane read requests are meta data read requests, we should make sure that all Control Plane Read timeout policies should throw a 503 on timeout. 

## ControlPlaneRetriableHotPath ##

Control Plane Retriable Hot Path policies are used in three different places. 

1. Partition Key Requests - which should not be retried. 
2. Address Requests - which should not be retried. 
2. Query Plan Requests - which should be retried.

## Default ##

All other cases use the Default HTTP Timeout Policy, including all data plane requests and some - but not all - meta data read/write requests. 
So of the 4 timeout policies that exist three need to have the ability to communicate that they should throw 503 errors on timeout. ControlPlaneRead, where it should always do that, and ControlPlaneRetriableHotPath + Default where we need to be flexible on when it can throw a 503 error on timeout.  

## Where are the Timeout Policies called? 

### ControlPlaneRead ###
1. Tests
2. GatewyaStoreClient
3. GatewayAccountReader

All of these methods should retry on a timeout. 

### ControlPlaneRetriableHotPath ###
1. Tests
2. GatewayAddressCache
3. HttpTimeoutPolcy `GetTimeoutPolicy` method. 

The tests the cases are mixed what ones should be retried. In the GatewayAddressCache they are address operations and therefore should not be retried. In the `GetTimeoutPolicy` method, only the case for the Query Plan operations should be able to retry. 

### Default ### 
1. Tests
2. HttpTimeoutPolcy `GetTimeoutPolicy` method. 

In the tests cases are mixed on which ones should be retired. In the `GetTimeoutPolicy` method, only meta data reads and data plane operations should be retried. 

So looking at where each of these timeout polices `GetTimeoutPolicy` method is the main method where it is decided which timeout policy is used. Right now it is really only deciding between the Default and ControlPlaneRetriableHotPath. The other policies are specified directly in the methods where the HTTP requests is made.  

# Proposed Solution #
Have two different instances  of each client in the construer with a flag that tells whether it should throw a 503 error on timeout or not. Then in the `GetTimeoutPolicy` method use the document service request to determine where it falls under the umbrella of the scenarios where we want to throw the 503 errors. By setting the flag on assignment of the policy, we can access this information anywhere in the flow of the HTTP gateway request.

So the new flow would be this: 

```mermaid
sequenceDiagram
    participant A as Operation
    participant B as ClientRetryPolicy <br> [Cross region retry]
    participant C as TransportHandler
    participant D as HttpTimeoutPolicy
    participant E as CosmosHttpClientCore
    A->>B: 1. Send HTTP operation
    B->>C: 
    C->>D: Wraps the call around retry layer
    D->>E: 
    E-->>D: OperationCanceledException
    D-->>E: Retries HTTP timeouts on same endpoint
    D-->>D: Repeats until retries exhausted
    D->>C: OperationCanceledException
    D-->>E: ShouldThrow503OnTimeout
    E-->>D: ServiceUnavailableException
    D->>C: ServiceUnavailableException
    C->>B: CosmosException(408)
    C->>B: CosmosException(503)
    B->>A: 
```

# Possible Downsides #
 Right now, if we want to add any other types of errors more flags would need to be added and more instances.
