### ISSUE TITLE
Subpartitioning: .NET test coverage and feature tracking

### ISSUE THREAD

**Issue by NaluTripician** [Azure/azure-cosmos-dotnet-v3#3616]
This is the current state of test/feature coverage in the .NET SDK in regard to subpartitioning.

| Feature | Is There Test Coverage? | Is there Negative Test Coverage? | Is the feature Implemented correctly (Pos/Neg)? |
--- | --- | ---| ---|
| Container Create | Yes | Yes | Yes |
| Container Delete | Yes | Not Needed*| Yes |
| Document Create | Yes | Yes | Yes |
| Document Delete | Yes | Yes| Yes |
| Document Read | Yes | Yes| Yes|
| Document Read Many | Yes| No | No, Test coverage will need to be updated once issue is fixed to reflect behavior|
| Document Replace Item | Yes | Yes| (Yes/No) |
| Document Upsert Item | Yes | Yes | (Yes/No) |
| Query | Yes| No | No, Test coverage will need to be updated once issue is fixed to reflect behavior| 

*Note Container Deletes do not need partition keys.
## To Do ##

- [x] Compete Test Coverage
- [x] Verify / assess current SDK behavior
- [x] Fill in feature gaps

**Comment by NaluTripician** [comment]
Updated test coverage in PR #3618. 

From these results it is not clear that a few features are not properly implemented. 

Document Read will accept incomplete partition keys. According to the design documents this should not be the case.

Document Read Many is not implemented and returns null items. 

Document Upsert Item has the same problem as Document Read. 

Document Replace item is functioning however the message in the Exception is unclear and should be changed to something similar to the message given in Document Delete: `Partition key provided either doesn't correspond to definition in the collection or doesn't match partition key field values specified in the document`

Queries are also not working.
