### ISSUE TITLE
Transportation Chaos Simulation - Fault Injection

### ISSUE THREAD

**Issue by NaluTripician** [Azure/azure-cosmos-dotnet-v3#3819]
# Fault Injection 

# Background
Currently the SDK does not have a way to simulate network issues. This makes it difficult to test the SDK's behavior when there are network issues. The goal of this feature is to allow customers to configure rules that specify how and when the SDK fails requests. This will allow customers to test the SDK's behavior when there are network issues. Additionally, this will help customers test their own retry policies.

# Design 

## `FaultInjectionRule`

To induce faults, we will introduce a new type `FaultInjectionRule`. This type will allow customers to configure how the SDK fails requests. Once created, `FaultInjectionRule`s can be added to specific containers. 

The `FaultInjectionRule` has three major components, `result`, `condition`, and 

### `result`

The `result` component of the `FaultInjectionRule` specifies what the result of the fault that is to be injected will be. The `result` component can be one of two types, `FaultInjectionServerErrorResult` or `FaultInjectionConnectionErrorResult`.

#### `FaultInjectionServerErrorResult`

Rule will return a server error to the customer. `FaultInjectionServerErrorResult` has three properties: `errorType`, `times`, and `delay`.

| Property | Description |
| -------- | ----------- |
| `errorType` | Required. The type of server error that the SDK will return to the customer. |
| `times` | An optional parameter that limits how many times the same rule can be applied on the operation. If `times` is not specified, the rule will be applied on the operation until the rule is removed or disabled from the container.
| `delay` | Required for `RESPONSE_DELAY` and `CONNECTION_DELAY` error types. The delay is the amount of time the SDK will wait before returning the error to the customer. |

##### **Supported server error types**

```
GONE
RETRY_WITH
INTERNAL_SERVER_ERROR
TOO_MANY_REQUESTS
READ_SESSION_NOT_AVAILABLE
TIMEOUT
PARTITION_IS_MIGRATING
RESPONSE_DELAY // used to simulate transient timeout/broken connections
CONNECTION_DELAY // used to simulate high channel acquisition.
```

#### `FaultInjectionConnectionErrorResult`

Rule will return a connection error to the customer. `FaultInjectionConnectionErrorResult` has three properties: `errorType`, `interval`, and `threshold`.

| Property | Description |
| -------- | ----------- |
| `errorType` | Required. The type of connection error that the SDK will return to the customer. |
| `interval` | Required. The interval is the amount of time the SDK will wait before returning the error to the customer. |
| `threshold` | Optional. `double` with value: (0-1]. Default value is 1. Percentage of established connections that will be impacted when connection error is injected. |

##### **Suported connection error types**
```
CONNECTION_CLOSE
CONNECTION_RESET
```

### `condition` 

The `condition` property of the `FaultInjectionRule` acts like a rule filter. A `FaultInjectionRule` will only be applied to a request if all the necessary conditions match. When a rule is configured, the SDK will pre-process the rule resolving the physical address if configured. The `condition` property is of type `FaultInjectionCondition` and has the following properties:

| Property | Default | Description |
| -------- | ----------- | ----------- |
| `OperationType` | `null` | Optional. For `FaultInjectionServerErrorResult`, `SERVER_GONE`, `SERVER_CONNECTION_DELAY`, and `FaultInjectionConnectionErrorResult`, ignore after resolving address. |
| `ConnectionType` | `null` | Optional. Specifies the connection type to which the rule will be applied: `Direct_Mode` or `Gateway_Mode` |
| `Region` | `null` | Optional. Specifies the region to which the rule will be applied. |
| `Endpoint` | `null` | Optional. Type of `FaultInjectionEndpoint`. Specifies the endpoint to which the rule will be applied. Use when filtering down to a subset of physical addresses. |

### `id`

Each `FaultInjectionRule` has a unique id. This id is used to identify the rule when disabling or removing the rule from the container. 

### Other components

| Property | Description |
| -------- | ----------- |
| `duration` | Optional. Defines how long the rule will be effective. If not specified, the rule will be effective until the rule is removed or disabled from the container. |
| `startDelay` | Optional. Defines how long the rule will wait before being effective. If not specified, the rule will be effective immediately. |
| `hitLimit` | Optional. Defines how many times the rule can be applied. If not specified, the rule will be applied to the request until the rule is removed or disabled from the container. |

### Multiple `FaultInjectionRule`s on a container

Each container can have multiple rules however, only one rule will be applied to a request. If a container has multiple rules applied to it, the first rule that matches the request will be applied. So even if multiple rules are defined, they many not see the effects happen at the same time. 

Additionally, it is important to note that becaue server error type rules are applied to the request while connection error type rules are happening on the background, the rule that is actually applied to the request will be determined by a time race condition. 

### How to add a `FaultInjectionRule`

To add `FaultInjectionRule`s to a container, a customer will use a new class `CosmosFaultInjectorHelper` and call the `configFaultInjectionRules` method which takes a `container` and a list of `FaultInjectionRule`s. 

```
CosmosFaultInjectorHelper.configFaultInjectionRules(CosmosContainer container, List<FaultInjectionRule> rules)
```

After configuting the rules, `regionEndpoint`s and `addresses` can be obtained from the rules.

```
serverErrorRule.getRegionEndpoint();
serverErrorRule.getAddresses();
```

### How to disable a `FaultInjectionRule`

To disable a `FaultInjectionRule`, a customer will call the `disable` method on the rule. 

```
serverErrorRule.disable();
```

### Get hit count of a `FaultInjectionRule`
To get the hit count of a `FaultInjectionRule`, a customer will call the `getHitCount` method on the rule. 

```
serverErrorRule.getHitCount();
```

## FaultInjection Request Flow

```mermaid
graph TD
    
    subgraph Request Flow
        Client ==> DocumentClient
        DocumentClient == GatewayMode==> GatewayStoreModel
        DocumentClient == DirectMode ==> ServerStoreModel     
        subgraph msdata
        ServerStoreModel ==> StoreClient
        StoreClient ==> ReplicatedResourceClient
        ReplicatedResourceClient ==> TransportClient
        TransportClient ==> ChannelDictonary
        ChannelDictonary ==> LoadBalancingChannel
        LoadBalancingChannel ==> LoadBalancingPartition
        LoadBalancingPartition ==> Channel
        Channel ==> Dispatcher
        Dispatcher ==> Connection
        end
    end
    subgraph FaultInjection Library
        EndpointBuilder -- FaultInjectionEndpoint --> ConditionBuilder
        ConditionBuilder -- FaultInjectionCondition --> RuleBuilder
        ResultBuilder -- FaultInjectionResult --> RuleBuilder -. List of Rules .->
        CosmosFaultInjectionHelper -- Creates --> ChaosInterceptorInstant(ChaosInterseptor)
        ChaosInterceptorInstant --> Container -- Set Interceptor --> DocumentClient
        DocumentClient -- Set Interceptor --> ServerStoreModel -- Set Interceptor --> StoreClient
        StoreClient -- Set Interceptor --> ReplicatedResourceClient -- Set Interceptor --> TransportClient
        TransportClient -- Get All Channels --> ChannelDictonary -- Get All Channels --> ChaosInterceptorInstant
        ChaosInterceptorInstant --> connTask(Create Connection Task)
        ChaosInterceptorInstant -- Create Rule Store --> RuleStore
        Container -.-> CosmosFaultInjectionHelper
        TransportClient -- Set Interceptor --> Channel -- Set Interceptor --> Dispatcher
        RuleStore -- All Rules Get Processed --> FaultInjectionProcessor
    end
    subgraph ChaosInterceptor
       subgraph OnChannelOpen
            FindRule0(Find Rule) -- ConnectionDelayRule --> openApp(RecordRuleApplication)
            openApp --> sleep0(Thread.Sleep)        
        end
        Channel-- "(activityId, serverUri, openingRequest)" -->OnChannelOpen
        subgraph OnRequestCall
            FindRule1(Find Rule) -- ServerResponseErrorRule --> errorApp(RecordRuleApplication) --> IsTimeout
            IsTimeout -- true --> sleep1(Thread.Sleep) --> ret0(Return Error)
            IsTimeout -- false --> ret0
            ret0 -- RntbdServerError --> Dispatcher
        end
        Dispatcher -- "(channelArgs)"--> OnRequestCall
        subgraph OnBeforeConnectionWrite
            FindRule2(Find Rule) --ServerResponseDelayRule --> delayAppB(RecordRuleApplication) --> sleep2(Thread.Sleep)
        end
        Dispatcher -- "(activityId)" --> OnBeforeConnectionWrite
        subgraph OnAfterConnectionWrite
            FindRule3(Find Rule) --ServerResponseDelayRule --> delayAppA(RecordRuleApplication) --> sleep3(Thread.Sleep)
        end
        Dispatcher -- "(activityId)" --> OnAfterConnectionWrite
        rsint(RuleStore)
        FindRule0 -.-> rsint -.-> FindRule0
        FindRule1 -.-> rsint -.-> FindRule1
        FindRule2 -.-> rsint -.-> FindRule2
        FindRule3 -.-> rsint -.-> FindRule3
    end

```
```[tasklist]
### Tasks
- [ ] https://github.com/Azure/azure-cosmos-dotnet-v3/issues/4256
- [ ] https://github.com/Azure/azure-cosmos-dotnet-v3/issues/4257
- [ ] https://github.com/Azure/azure-cosmos-dotnet-v3/issues/4258
- [ ] https://github.com/Azure/azure-cosmos-dotnet-v3/issues/4259
- [ ] https://github.com/Azure/azure-cosmos-dotnet-v3/issues/4795
```

**Comment by philipthomas-MSFT** [comment]
Hotfix release for Direct package
