### ISSUE TITLE
[Internal] AllVersionsAndDeletes on change feed pull model for benchmarking design documentation and implementation

### ISSUE THREAD

**Issue by philipthomas-MSFT** [Azure/azure-cosmos-dotnet-v3#3942]
# Purpose statement

This is a document to enhance the Cosmos DB experience by achieving even higher performance.

**Description**: 

**Level-setting**

# Tasks
- [ ] Identifying stakeholders
- [ ] Describing the testing strategy
- [ ] Providing visual aids (diagrams, flow charts, C4, etc.)
- [ ] Estimating time to complete PR

# Stakeholders
- Azure Cosmos DB .NET SDK for NoSQL
  - Philip Thomas
- Compute Gateway
  - Philip Thomas
  - Dmitri Melnikov
- Backend
  - Gopal Rander
  - Michael Koltachev
- Materialized View
  -  Hemeswari Varada
  - Sarwesh Krishnan
  - Abhijit P. Pai
- Other collaborations
  - Kiran Kumar Koli
  - Justin Cocchi

# Resources
# Out of scope
# Scope of work
#### Areas of impact
# Estimation for deliverables
#### Supportability
# Testing
