### ISSUE TITLE
[Internal] AllVersionsAndDeletes on change feed pull model for partition split EpkRange and IncomingPartitionKeyRangeId Validation. Compute Gateway.

### ISSUE THREAD

**Issue by philipthomas-MSFT** [Azure/azure-cosmos-dotnet-v3#3980]
# Purpose statement

This is a document to enhance the Cosmos DB experience by achieving even higher data integrity by sending notifications to SDK client that split partitions having happened in Compute Gateway and vice versa so that refreshes on PartitionKeyRangeCache are forced, thus keeping the SDK client and Compute Gateway in sync. It also includes how Epk ranges are handled and set in requests to the backend.

**Description**: 

**Level-setting**

- What is change feed?
  - https://learn.microsoft.com/en-us/azure/cosmos-db/change-feed
  - Pull model?
    - Read changes from a particular partition key
    - Control the pace at which your client receives changes for processing
    - Perform a one-time read of the existing data in the change feed (for example, to do a data migration)
    - https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/change-feed-pull-model?tabs=dotnet
- What is AllVersionsAndDeletes?
  - All versions and deletes mode (preview) is a persistent record of all changes to items from create, update, and delete operations. You get a record of each change to items in the order that it occurred, including intermediate changes to an item between change feed reads.
  - https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/change-feed-modes?tabs=latest-version#all-versions-and-deletes-change-feed-mode-preview
- What is physical partition split handling?
  - When a physical partition is split, the original, now archived parent partition does not exist and will yield a [Gone](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/410) (410) http status code when any change feed requests are attempted by the caller, or SDK client. All change feed requests must be properly routed to the appropriate live child partition in order to receive documents. Additional logic is required in order to request [AllVersionsAndDeletes (preview)](https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/change-feed-modes?tabs=latest-version#all-versions-and-deletes-change-feed-mode-preview) meta data along with the documents.
  - https://learn.microsoft.com/en-us/azure/cosmos-db/partitioning-overview

# Tasks
- [x] Identifying stakeholders
- [x] Understanding source current architecture
- [x] Detailing the target future architecture and gaps
- [x] Describing the testing strategy
- [x] Identifying performance and security concerns
- [x] Defining out of scope and future states
- [ ] Architecture katas
- [x] Outlining supportability, manageability, and configuration
- [x] Providing visual aids (diagrams, flow charts, C4, etc.)
- [x] Estimating time to complete PR
- [x] Managing and configuring the feature flag

# Stakeholders
- Azure Cosmos DB .NET SDK for NoSQL
  - Philip Thomas
- Compute Gateway
  - Philip Thomas
  - Dmitri Melnikov
- Backend
  - Gopal Rander
  - Michael Koltachev
- Materialized View
  -  Hemeswari Varada
  - Sarwesh Krishnan
  - Abhijit P. Pai
- Other collaborations
  - Kiran Kumar Koli
  - Justin Cocchi

# Resources

![AllVersionsAndDeletes Change Feed Flow](https://github.com/Azure/azure-cosmos-dotnet-v3/assets/86612891/b9471296-3327-4d0d-a330-3c535ff288a3)

# Out of scope
- Incremental ([LatestVersion](https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/change-feed-modes?tabs=latest-version#latest-version-change-feed-mode)) change feed mode.
- There are no public facing contracts that need to be updated, deleted or added with one caveat. There is a possibility that force refresh cache and feature flag could be driven by logic within the SDK client, but more discussions need to be made first. My first reaction would be no, because this is a major performance boost, there is no need to have consumers opt-out.

# Scope of work
The SDK client needs to be notified if **x-ms-documentdb-partitionkeyrangeid** has split on Compute Gateway so that the SDK client can refresh it's _PartitionKeyRangeCache_ while in [AllVersionsAndDeletes (preview)](https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/change-feed-modes?tabs=latest-version#all-versions-and-deletes-change-feed-mode-preview) change feed mode.

The Compute Gateway needs to be notified if **x-ms-documentdb-partitionkeyrangeid** has split on SDK client so that the Compute Gateway can refresh it's _PartitionKeyRangeCache_ while in [AllVersionsAndDeletes (preview)](https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/change-feed-modes?tabs=latest-version#all-versions-and-deletes-change-feed-mode-preview) change feed mode.

The Compute Gateway needs to include **x-ms-start-epk** and **x-ms-end-epk** when **x-ms-read-key-type** is null or not equal to "EffectivePartitionKeyRange" with all CF requests while in [AllVersionsAndDeletes (preview)](https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/change-feed-modes?tabs=latest-version#all-versions-and-deletes-change-feed-mode-preview) change feed mode.

.NET, Java and Sparks will send the following:
**x-ms-documentdb-partitionkeyrangeid**
or 
**x-ms-documentdb-partitionkeyrangeid
x-ms-start-epk
x-ms-end-epk**

There will not be a case when the request will not have **x-ms-documentdb-partitionkeyrangeid**, so there will not be a need to do a lookup using **x-ms-start-epk** and **x-ms-end-epk**.

## Criteria
When the **x-ms-documentdb-partitionkeyrangeid** is not part of the _PartitionKeyRangeCache_, Refresh _PartitionKeyRangeCache_.
When the **x-ms-documentdb-partitionkeyrangeid** is part of the _PartitionKeyRangeCache's parents_, Throw PartitionKeyRangeGoneExeption.
When the **x-ms-read-key-type** in request headers is null or not equal to "EffectivePartitionKeyRange", set **x-ms-read-key-type**, **x-ms-start-epk**, and **x-ms-end-epk** for the drain route CF request.

#### Branch
- **msdata**
  -  [users/philipthomas/ffcf_split_handling_base_improvements](https://msdata.visualstudio.com/DefaultCollection/CosmosDB/_git/CosmosDB?version=GBusers%2Fphilipthomas%2Fffcf_split_handling_base_improvements)

#### Performance
- Latency
#### Security
- No security concerns at the time of document creation.

#### Areas of impact

- [ ] PR#1

# Estimation for deliverables
- 1-2 days coding per PR
- 1-2 days testing per PR
- 5+ days awaiting per PR approval

##### Client telemetry
- No relevancy

##### Distributed tracing
- No relevancy

##### Diagnostic logging
- No relevancy

# Testing
### Unit (Gated pipeline)
- Compute Gateway only, not SDK.
### Emulator (Gated pipeline)
- Internal emulator that runs with Compute Gateway pipeline, not public emulator with SDK.
### Performance/Benchmarking (Gated pipeline)
- We need to get a baseline of how change feed requests perform while in [AllVersionsAndDeletes (preview)](https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/change-feed-modes?tabs=latest-version#all-versions-and-deletes-change-feed-mode-preview) change feed mode.
### Security/Penetration (Gated pipeline)
- Not required.

# Concerns
