### ISSUE TITLE
Gallium Semester Tasks

### ISSUE THREAD

**Issue by kundadebdatta** [Azure/azure-cosmos-dotnet-v3#4246]
This is a master task list of all the items identified as a part of the Gallium semester deliverables. The tasks are listed below:

List of the work-items. 
  
- [ ] #3782 Cross Region Hedging (Thompson Sampling for Speculative Retry). => @NaluTripician is currently working on this.
- [ ] #3819 Transport chaos simulation. => @NaluTripician currently working on it. 

- **Upgrade follow-ups:**
    - [ ] #4244 => @kundadebdatta and @NaluTripician to Analyze and Scope.
    - [ ] #4245 => @kundadebdatta and @NaluTripician to Analyze and Scope.
   
- **Per Partition Automatic Failover:**
    - [ ] #3499 . => @philipthomas-MSFT, @kundadebdatta to Analyzing this currency.
    - [x] #3978 . => @kundadebdatta has completed this item and merged the fix.
    - [x] #3981  => @kundadebdatta has completed this item and merged the fix.
    - [ ] #3977  => @kundadebdatta to Analyze and Scope.
    - [x] #4181 => @kundadebdatta has completed this item and merged the fix.
    - [ ] #4236  => @kundadebdatta is currently working on this.
   
- **Supportability:**
    - [ ] ClientTelemetry => Debdatta to analyze and scope. (Should be prioritized)
    - [ ] Diagnostics (any missing context) => Debdatta to analyze and scope.
    - [ ] Compaction => Backlog Item - Ways to reduce the diagnostics content.
    
- **Reliable Writes:**
    - [ ] Prioritize brute force logic. => Debdatta to Analyze and Scope.
    - [ ] Non-brute-force logic => Backlog
    
- **Caches:** Guaranteed address refreshes (decouple from CX CancellationToken's) => Nalu to Analyze and Pick Up.

- **DNS** -> IP handling (Caching etc.)
    - [ ] DNS outage, Compute corss-federtation routing etc.  => Nalu to Experiment/ Analysis: Can we do DNS to IP mapping ourselves. (Last good known). Right now, waiting on clarifications.
 
 
**Other Miscellaneous Tasks:**
 
- Connection sharing between clients.
- Patch and Bulk in the same library.
