### ISSUE TITLE
HA Direct stack Improvements

### ISSUE THREAD

**Issue by kirankumarkolli** [Azure/azure-cosmos-dotnet-v3#4703]
```[tasklist]
### Work items
- [ ] QuorumReader: Support 2-replica state
- [ ] LeaseLost: Force cross region retry immediately
- [ ] 410/3092: Force cross region retry
- [ ] 408 (Reads): Force cross region retry
- [ ] 404/1002: Bail fast in local region
```

**Comment by kirankumarkolli** [comment]
Related: #4702
