### ISSUE TITLE
Hybrid search support

### ISSUE THREAD

**Issue by kirankumarkolli** [Azure/azure-cosmos-dotnet-v3#4824]
Hybrid search support

```[tasklist]
### Tasks
- [ ] https://github.com/Azure/azure-cosmos-dotnet-v3/issues/4823
- [ ] https://github.com/Azure/azure-cosmos-dotnet-v3/issues/4628
- [ ] https://github.com/Azure/azure-cosmos-dotnet-v3/pull/4794
- [ ] https://github.com/Azure/azure-cosmos-dotnet-v3/pull/4798
```
